import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

function read(relativePath: string) {
  return fs.readFileSync(path.join(process.cwd(), relativePath), 'utf8');
}

const studioPanelSource = read('src/components/studio/StudioPanel.tsx');
const pageSource = read('src/app/page.tsx');
const switcherSource = read('src/components/studio/StudioToolSwitcher.tsx');
const presentationPanelSource = read('src/components/studio/PresentationPanels.tsx');
const structuredPresentationPanelSource = read('src/components/studio/StructuredPresentationPanel.tsx');
const structuredOutlineDraftSource = read('src/components/studio/StructuredPresentationOutlineDraft.tsx');
const pptV2RouteSource = read('src/app/api/ai/ppt-v2/route.ts');
const presentationModeSelectorSource = read('src/components/studio/PresentationModeSelector.tsx');
const knowledgeMapPanelSource = read('src/components/studio/KnowledgeMapPanel.tsx');
const knowledgeMapWorkspaceSource = read('src/components/studio/KnowledgeMapWorkspace.tsx');
const virtualClassroomPanelSource = read('src/components/studio/VirtualClassroomPanel.tsx');
const paperSearchPanelPath = path.join(process.cwd(), 'src/components/studio/PaperSearchPanel.tsx');
assert.ok(fs.existsSync(paperSearchPanelPath), 'Paper search product should provide a real Studio panel');
const paperSearchPanelSource = fs.readFileSync(paperSearchPanelPath, 'utf8');
const deepResearchPanelPath = path.join(process.cwd(), 'src/components/studio/DeepResearchPanel.tsx');
assert.ok(fs.existsSync(deepResearchPanelPath), 'Deep research product should provide a real Studio panel');
const deepResearchPanelSource = fs.readFileSync(deepResearchPanelPath, 'utf8');
const hypothesisPanelPath = path.join(process.cwd(), 'src/components/studio/HypothesisGenerationPanel.tsx');
assert.ok(fs.existsSync(hypothesisPanelPath), 'Hypothesis generation should provide a real Studio panel');
const hypothesisPanelSource = fs.readFileSync(hypothesisPanelPath, 'utf8');
const dataProcessingPanelPath = path.join(process.cwd(), 'src/components/studio/DataProcessingPanel.tsx');
assert.ok(fs.existsSync(dataProcessingPanelPath), 'Data processing should provide a real Studio panel');
const dataProcessingPanelSource = fs.readFileSync(dataProcessingPanelPath, 'utf8');
const experimentDesignPanelPath = path.join(process.cwd(), 'src/components/studio/ExperimentDesignPanel.tsx');
assert.ok(fs.existsSync(experimentDesignPanelPath), 'Experiment design should provide a real Studio panel');
const experimentDesignPanelSource = fs.readFileSync(experimentDesignPanelPath, 'utf8');
const academicWritingPanelPath = path.join(process.cwd(), 'src/components/studio/AcademicWritingPanel.tsx');
assert.ok(fs.existsSync(academicWritingPanelPath), 'Academic writing should provide a real Studio panel');
const academicWritingPanelSource = fs.readFileSync(academicWritingPanelPath, 'utf8');
const textPolishingPanelPath = path.join(process.cwd(), 'src/components/studio/TextPolishingPanel.tsx');
assert.ok(fs.existsSync(textPolishingPanelPath), 'Text polishing should provide a real Studio panel');
const textPolishingPanelSource = fs.readFileSync(textPolishingPanelPath, 'utf8');
const scientificIllustrationPanelPath = path.join(process.cwd(), 'src/components/studio/ScientificIllustrationPanel.tsx');
assert.ok(fs.existsSync(scientificIllustrationPanelPath), 'Scientific illustration should provide a real Studio panel');
const scientificIllustrationPanelSource = fs.readFileSync(scientificIllustrationPanelPath, 'utf8');
const peerReviewPanelPath = path.join(process.cwd(), 'src/components/studio/PeerReviewPanel.tsx');
assert.ok(fs.existsSync(peerReviewPanelPath), 'Peer review should provide a real Studio panel');
const peerReviewPanelSource = fs.readFileSync(peerReviewPanelPath, 'utf8');
const discoverSourcesModalSource = read('src/components/library/DiscoverSourcesModal.tsx');
const virtualClassroomWorkspaceSource = read('src/components/studio/VirtualClassroomWorkspace.tsx');
const workbenchTopBarSource = read('src/components/workbench/WorkbenchTopBar.tsx');
const realPptArtifactSource = read('scripts/generate-real-ppt-v2-artifact.mjs');
const taxonomyPath = path.join(process.cwd(), 'src/lib/studio-research-taxonomy.ts');
assert.ok(fs.existsSync(taxonomyPath), 'Studio research taxonomy should define the four user-approved research categories');
const taxonomySource = fs.readFileSync(taxonomyPath, 'utf8');
const productCenterSource = `${studioPanelSource}\n${switcherSource}`;
const retainedSource = `${productCenterSource}\n${presentationPanelSource}\n${virtualClassroomPanelSource}\n${virtualClassroomWorkspaceSource}`;

const studioPanelStart = studioPanelSource.indexOf('export function StudioPanel');
const panelContentStart = studioPanelSource.indexOf('{activeTab ===', studioPanelStart);
assert.ok(studioPanelStart >= 0, 'StudioPanel export not found');
assert.ok(panelContentStart > studioPanelStart, 'StudioPanel content switch not found');

const navSection = studioPanelSource.slice(studioPanelStart, panelContentStart);
assert.match(navSection, /<StudioToolSwitcher[\s\S]*activeTab=\{activeTab\}[\s\S]*onSelect=\{onSelect\}[\s\S]*navItems=\{visibleNavItems\}/, 'StudioPanel should remain a side-effect-free tool directory');
assert.match(navSection, /getVisibleStudioNav\(hideVirtualClassroom\)/, 'StudioPanel should derive visible navigation from mounted embed state');
assert.match(switcherSource, /params\.get\('hideVirtualClassroom'\)/, 'Studio visibility should honor the explicit hide flag');
assert.match(switcherSource, /params\.get\('embed'\) === 'research-agent'/, 'Research-agent embed should hide the duplicate virtual classroom entry');
assert.match(switcherSource, /STUDIO_NAV\.filter\(item => item\.id !== 'virtual-classroom'\)/, 'Only the virtual classroom product should be filtered');
assert.match(switcherSource, /onClick=\{\(\) => onSelect\(item\.id\)\}/, 'Studio tool switcher should only request active tab changes');
assert.doesNotMatch(navSection, /queueStudioPrompt|fetch\(|handleGenerate|generate|\/api\/ai\//, 'Studio nav must not trigger generation side effects');
assert.doesNotMatch(switcherSource, /queueStudioPrompt|fetch\(|handleGenerate|generate|\/api\/ai\//, 'Studio tool switcher must not trigger generation side effects');
assert.match(pageSource, /function openStudioWorkspace\(tab: StudioTab\)/, 'Workbench should expose one side-effect-free tool opening action');
assert.match(pageSource, /function closeStudioWorkspace\(\)/, 'Workbench should expose an immediate return to document chat');
assert.match(pageSource, /sessionStorage\.setItem\(ACTIVE_TOOL_STORAGE_KEY, tab\)/, 'Workbench should preserve the active tool across refresh');
assert.match(studioPanelSource, /export function StudioWorkspacePanel/, 'Studio should expose the focused workspace independently from the right directory');
assert.match(studioPanelSource, /data-testid="studio-back-to-chat"/, 'Focused workspaces should provide a stable return action');
assert.match(studioPanelSource, /data-testid="studio-back-to-chat"[\s\S]*?<span>返回文献问答<\/span>/, 'Focused workspaces should label the return destination without relying on an icon alone');
assert.match(studioPanelSource, /data-testid="studio-directory-scroll"/, 'The product directory should own its scrolling');
assert.match(studioPanelSource, /data-testid="studio-workspace-scroll"/, 'The focused workspace should own its scrolling');
assert.doesNotMatch(studioPanelSource, /切换入口只打开对应工作区，检索或生成需在下方明确操作。/, 'Studio should not describe the removed appended-workspace interaction');

assert.match(taxonomySource, /id: 'literature-evidence', label: '文献证据'/, 'Taxonomy should define literature evidence');
assert.match(taxonomySource, /id: 'research-ideation', label: '研究构思'/, 'Taxonomy should define research ideation even while it has no ready product');
assert.match(taxonomySource, /id: 'results-expression', label: '成果表达'/, 'Taxonomy should define results expression');
assert.match(taxonomySource, /id: 'collaboration-memory', label: '协作沉淀'/, 'Taxonomy should define collaboration and memory');
assert.match(taxonomySource, /id: 'knowledge'[\s\S]*label: '研究脉络'[\s\S]*categoryId: 'literature-evidence'/, 'Original knowledge map should be mapped as research context under literature evidence');
assert.match(taxonomySource, /id: 'paper-search'[\s\S]*label: '论文检索'[\s\S]*categoryId: 'literature-evidence'[\s\S]*availability: 'ready'/, 'Paper search should be a real literature-evidence product');
assert.match(taxonomySource, /id: 'deep-research'[\s\S]*label: '深度研究'[\s\S]*categoryId: 'literature-evidence'[\s\S]*availability: 'ready'/, 'Deep research should be a real literature-evidence product');
assert.match(taxonomySource, /id: 'hypothesis-generation'[\s\S]*label: '假设生成'[\s\S]*categoryId: 'research-ideation'[\s\S]*availability: 'ready'/, 'Hypothesis generation should make research ideation visible through a real product');
assert.match(taxonomySource, /id: 'data-processing'[\s\S]*label: '数据处理'[\s\S]*categoryId: 'research-ideation'[\s\S]*availability: 'ready'/, 'Data processing should be a real research-ideation product');
assert.match(taxonomySource, /id: 'experiment-design'[\s\S]*label: '实验设计'[\s\S]*categoryId: 'research-ideation'[\s\S]*availability: 'ready'/, 'Experiment design should be a real research-ideation product');
assert.match(taxonomySource, /id: 'academic-writing'[\s\S]*label: '学术写作'[\s\S]*categoryId: 'results-expression'[\s\S]*availability: 'ready'/, 'Academic writing should be a real results-expression product');
assert.match(taxonomySource, /id: 'text-polishing'[\s\S]*label: '文本润色'[\s\S]*categoryId: 'results-expression'[\s\S]*availability: 'ready'/, 'Text polishing should be a real results-expression product');
assert.match(taxonomySource, /id: 'scientific-illustration'[\s\S]*label: '科研绘图'[\s\S]*categoryId: 'results-expression'[\s\S]*availability: 'ready'/, 'Scientific illustration should be a real results-expression product');
assert.match(taxonomySource, /id: 'presentation'[\s\S]*label: 'PPT 制作'[\s\S]*categoryId: 'results-expression'/, 'Original presentation product should be mapped as PPT creation under results expression');
assert.match(taxonomySource, /id: 'peer-review'[\s\S]*label: '论文审查'[\s\S]*categoryId: 'collaboration-memory'[\s\S]*availability: 'ready'/, 'Peer review should be a real collaboration product');
assert.match(taxonomySource, /id: 'virtual-classroom'[\s\S]*label: '虚拟课堂'[\s\S]*categoryId: 'collaboration-memory'[\s\S]*availability: 'runtime-dependent'/, 'Virtual classroom should be mapped under collaboration without being marked ready');
const productDefinitions = taxonomySource.slice(taxonomySource.indexOf('STUDIO_RESEARCH_PRODUCTS'));
assert.equal((productDefinitions.match(/\n\s+id: '/g) || []).length, 12, 'Taxonomy should expose scientific illustration and the eleven existing real products');
assert.match(switcherSource, /getVisibleStudioCategories/, 'Product center should render taxonomy categories through the empty-category filter');
assert.match(switcherSource, /grid-cols-2/, 'Product cards should use a compact two-column layout so the mobile workspace keeps usable height');
assert.doesNotMatch(switcherSource, /max-h-\[36vh\]|overflow-y-auto/, 'Product navigation should remain fully visible before the active workspace');
assert.doesNotMatch(switcherSource, /即将上线|敬请期待|coming soon/i, 'Product center must not render placeholder products');
assert.doesNotMatch(productCenterSource, /presentation2/, 'Structured PPT should remain a mode inside the original presentation product, not a hidden fourth product');
assert.doesNotMatch(productCenterSource, /核心产物|科研产物|更多工具|练习工具/, 'Product center should not keep the later grouping labels');
assert.doesNotMatch(workbenchTopBarSource, /科研产物/, 'Workbench copy should not reintroduce the removed research-artifact concept');
assert.doesNotMatch(productCenterSource, /互动页面|测验练习|项目研习|组会材料|实验记录|Results 初稿|Discussion 初稿/, 'Later artifact tools should not remain in the product center');
assert.doesNotMatch(productCenterSource, /STUDIO_ARTIFACT_TOOLS|StudioArtifactToolPanel|studio-tools/, 'Product center should not retain the later artifact registry or panel');

assert.ok(!fs.existsSync(path.join(process.cwd(), 'src/components/studio/StudioArtifactToolPanel.tsx')), 'Removed artifact panel should not remain as dead code');
assert.ok(!fs.existsSync(path.join(process.cwd(), 'src/components/studio/KnowledgeCardPanel.tsx')), 'Unreachable legacy knowledge-card panel should not remain beside the active knowledge-map product');
assert.ok(!fs.existsSync(path.join(process.cwd(), 'src/lib/studio-tools.ts')), 'Removed artifact registry should not remain as dead code');
assert.ok(!fs.existsSync(path.join(process.cwd(), 'src/lib/studio-tool-api-contract.ts')), 'Removed artifact API contract should not remain as dead code');
assert.ok(!fs.existsSync(path.join(process.cwd(), 'src/app/api/ai/studio-tool/route.ts')), 'Removed artifact API route should not remain without a product consumer');

assert.match(studioPanelSource, /activeTab === 'presentation' && <PresentationWorkspacePanel \/>/, 'PPT product should render its original workspace');
assert.match(studioPanelSource, /activeTab === 'knowledge' && <KnowledgeMapPanel \/>/, 'Knowledge map product should render its original panel');
assert.match(studioPanelSource, /activeTab === 'paper-search' && <PaperSearchPanel \/>/, 'Paper search product should render its real search panel');
assert.match(studioPanelSource, /activeTab === 'deep-research' && <DeepResearchPanel \/>/, 'Deep research product should render its real report panel');
assert.match(studioPanelSource, /activeTab === 'hypothesis-generation' && <HypothesisGenerationPanel \/>/, 'Hypothesis generation should render its real evidence-backed panel');
assert.match(studioPanelSource, /activeTab === 'data-processing' && <DataProcessingPanel \/>/, 'Data processing should render its real table-plan panel');
assert.match(studioPanelSource, /activeTab === 'experiment-design' && <ExperimentDesignPanel \/>/, 'Experiment design should render its grounded protocol panel');
assert.match(studioPanelSource, /activeTab === 'academic-writing' && <AcademicWritingPanel \/>/, 'Academic writing should render its grounded drafting panel');
assert.match(studioPanelSource, /activeTab === 'text-polishing' && <TextPolishingPanel \/>/, 'Text polishing should render its protected revision panel');
assert.match(studioPanelSource, /activeTab === 'scientific-illustration' && <ScientificIllustrationPanel \/>/, 'Scientific illustration should render its real image panel');
assert.match(studioPanelSource, /activeTab === 'peer-review' && <PeerReviewPanel \/>/, 'Peer review should render its read-only review panel');
assert.match(studioPanelSource, /activeTab === 'virtual-classroom' && <VirtualClassroomPanel \/>/, 'Virtual classroom should render its original panel');
assert.match(paperSearchPanelSource, /<DiscoverSourcesModal[\s\S]*variant="embedded"/, 'Paper search should reuse the existing discover and ingest workspace');
assert.match(discoverSourcesModalSource, /待核验/, 'Search results should state their verification boundary');
assert.match(deepResearchPanelSource, /\/api\/ai\/deep-research/, 'Deep research should call its grounded server route');
assert.match(deepResearchPanelSource, /AbortController/, 'Deep research should expose client-side cancellation');
assert.match(deepResearchPanelSource, /StudioEvidenceStatusPanel/, 'Deep research should render reusable evidence links');
assert.match(hypothesisPanelSource, /\/api\/ai\/hypothesis-generation/, 'Hypothesis generation should call its grounded server route');
assert.match(hypothesisPanelSource, /AbortController/, 'Hypothesis generation should expose client-side cancellation');
assert.match(hypothesisPanelSource, /StudioEvidenceStatusPanel/, 'Hypothesis generation should render reusable evidence links');
assert.match(hypothesisPanelSource, /可证伪|证伪/, 'Hypothesis cards should expose falsifiable predictions');
assert.match(dataProcessingPanelSource, /\/api\/data-processing\/plan/, 'Data processing should call its dedicated server route');
assert.match(dataProcessingPanelSource, /AbortController/, 'Data processing should support request cancellation');
assert.match(dataProcessingPanelSource, /buildDataTablePreviewForPaper/, 'Data processing should read real CSV or XLSX summaries before planning');
assert.match(dataProcessingPanelSource, /下载方案/, 'Data processing should expose a downloadable reproducible artifact');
assert.match(experimentDesignPanelSource, /\/api\/ai\/experiment-design/, 'Experiment design should call its grounded server route');
assert.match(experimentDesignPanelSource, /AbortController/, 'Experiment design should expose client-side cancellation');
assert.match(experimentDesignPanelSource, /StudioEvidenceStatusPanel/, 'Experiment design should render reusable evidence links');
assert.match(experimentDesignPanelSource, /下载预注册协议/, 'Experiment design should expose a downloadable preregistration artifact');
assert.match(academicWritingPanelSource, /\/api\/ai\/academic-writing/, 'Academic writing should call its grounded server route');
assert.match(academicWritingPanelSource, /AbortController/, 'Academic writing should expose client-side cancellation');
assert.match(academicWritingPanelSource, /StudioEvidenceStatusPanel/, 'Academic writing should render reusable evidence links');
assert.match(academicWritingPanelSource, /下载 Markdown 草稿/, 'Academic writing should expose an editable text artifact');
assert.match(textPolishingPanelSource, /\/api\/ai\/text-polishing/, 'Text polishing should call its dedicated server route');
assert.match(textPolishingPanelSource, /AbortController/, 'Text polishing should expose cancellation');
assert.match(textPolishingPanelSource, /恢复原文/, 'Text polishing should provide an explicit reversible action');
assert.match(textPolishingPanelSource, /下载修订记录/, 'Text polishing should expose a downloadable revision artifact');
assert.match(scientificIllustrationPanelSource, /\/api\/ai\/scientific-illustration/, 'Scientific illustration should call its dedicated server route');
assert.match(scientificIllustrationPanelSource, /AbortController/, 'Scientific illustration should expose cancellation');
assert.match(scientificIllustrationPanelSource, /下载图片/, 'Scientific illustration should expose a downloadable image file');
assert.match(scientificIllustrationPanelSource, /不是数据图表/, 'Scientific illustration should expose its schematic-only boundary');
assert.match(peerReviewPanelSource, /\/api\/ai\/peer-review/, 'Peer review should call its dedicated server route');
assert.match(peerReviewPanelSource, /AbortController/, 'Peer review should expose cancellation');
assert.match(peerReviewPanelSource, /StudioEvidenceStatusPanel/, 'Peer review should render reusable evidence links');
assert.match(peerReviewPanelSource, /只读审查|不会直接改稿/, 'Peer review should clearly preserve the read-only boundary');
assert.match(peerReviewPanelSource, /下载审查报告/, 'Peer review should expose a downloadable report');
assert.match(retainedSource, /data-testid="virtual-classroom-open"/, 'Virtual classroom needs a full-page entry for real use');
assert.match(retainedSource, /data-testid="virtual-classroom-iframe"/, 'Virtual classroom should embed the classroom runtime in Studio');
assert.match(retainedSource, /NEXT_PUBLIC_VIRTUAL_CLASSROOM_ORIGIN/, 'Virtual classroom origin should remain configurable');
assert.doesNotMatch(retainedSource, /参考 OpenMAIC|OpenMAIC 对齐|grounded retrieval|grounded context|citation audit/i, 'User-facing Studio copy must not expose reference names or implementation jargon');
assert.doesNotMatch(realPptArtifactSource, /OpenMAIC|openmaic|OPENMAIC/, 'Generated PPT content must not expose internal reference names');

assert.match(presentationPanelSource, /data-testid="image-ppt-generate"/, 'Image PPT still needs an explicit generate button');
assert.match(structuredPresentationPanelSource, /data-testid="academic-ppt-generate"/, 'Structured PPT still needs an explicit generate button');
assert.match(structuredPresentationPanelSource, /StructuredPresentationOutlineDraft/, 'Structured PPT should use the editable outline draft before generation');
assert.match(structuredOutlineDraftSource, /data-testid="academic-ppt-outline-confirm"/, 'Structured PPT outline draft needs an explicit confirmation button');
assert.match(structuredPresentationPanelSource, /请先检查并确认下方简报大纲/, 'Structured PPT generation should require outline confirmation');
assert.match(structuredPresentationPanelSource, /outlineDraft,/, 'Structured PPT should send the confirmed outline draft to the backend');
assert.match(structuredOutlineDraftSource, /buildPptOutlineDraft/, 'Structured PPT outline draft should reuse the shared outline contract');
assert.match(pptV2RouteSource, /sanitizePptOutlineDraft\(body\.outlineDraft\)/, 'PPT-v2 route should sanitize the user-edited outline draft');
assert.match(pptV2RouteSource, /formatPptOutlineDraftForPrompt\(outlineDraft\)/, 'PPT-v2 route should format the outline draft for generation prompts');
assert.match(pptV2RouteSource, /outlineDraftApplied/, 'PPT-v2 observability should report whether a confirmed outline was applied');
assert.doesNotMatch(structuredPresentationPanelSource, /ArcDeck|真实模型/, 'Structured PPT panel should not expose implementation jargon');
assert.match(presentationModeSelectorSource, /data-testid=\{`presentation-mode-\$\{option\.id\}`\}/, 'PPT mode selector should expose stable test ids');
assert.match(presentationModeSelectorSource, /<span>PPT 制作<\/span>/, 'PPT detail panel should use the approved product name');
assert.doesNotMatch(`${knowledgeMapPanelSource}\n${knowledgeMapWorkspaceSource}`, /['">]资料脉络[<'"]/, 'Knowledge-map UI should consistently use the approved research-context name');
assert.match(virtualClassroomPanelSource, /课堂服务未连接/, 'Virtual classroom should expose its unavailable runtime state');
assert.match(presentationModeSelectorSource, /id: 'image'[\s\S]*label: '图片页简报'/, 'PPT mode selector should keep the image PPT option');
assert.match(presentationModeSelectorSource, /id: 'structured'[\s\S]*label: '结构化 PPT'/, 'PPT mode selector should keep the structured PPT option');

console.log(JSON.stringify({
  ok: true,
  checked: 'Studio product center exposes scientific illustration and the existing real products without navigation side effects',
  products: ['论文检索', '深度研究', '研究脉络', '假设生成', '数据处理', '实验设计', '学术写作', '文本润色', '科研绘图', 'PPT 制作', '论文审查', '虚拟课堂'],
  explicitButtons: ['discover-search', 'deep-research-start', 'hypothesis-generation-start', 'data-processing-start', 'experiment-design-start', 'academic-writing-start', 'text-polishing-start', 'scientific-illustration-start', 'image-ppt-generate', 'academic-ppt-generate', 'peer-review-start', 'virtual-classroom-open'],
}, null, 2));
